export default {
    inherit: {
        type: 'ww-layout',
    },
    options: {
        displayAllowedValues: ['flex', 'grid', 'inline-flex', 'inline-grid'],
    },
    editor: {
        label: { en: 'Chat AI' },
        icon: 'chat',
        customSettingsPropertiesOrder: [
            {
                label: 'Behavior',
                isCollapsible: true,
                properties: [
                    'messages',
                    'initialMessages',
                    'disabled',
                    'apiMode',
                    'apiEndpoint',
                    'apiAuthToken',
                    'apiHeaders',
                    'modelName',
                    'isLoading',
                    'isStreaming',
                ],
            },
            {
                label: 'Files',
                isCollapsible: true,
                properties: [
                    'allowAttachments',
                    'acceptedFileTypes',
                    'maxFileSizeMb',
                    'maxFilesPerMessage',
                    'allowMultipleFiles',
                    'showFilePreviews',
                ],
            },
            {
                label: 'Text',
                isCollapsible: true,
                properties: [
                    'userLabel',
                    'assistantLabel',
                    'placeholder',
                    'inputPlaceholder',
                    'emptyMessageText',
                    'loadingText',
                    'errorText',
                    'enableMarkdown',
                    'enableCopyButton',
                    'enableRetryButton',
                    'enableClearButton',
                ],
            },
            {
                label: 'Message mappings',
                isCollapsible: true,
                properties: [
                    'mappingMessageId',
                    'mappingMessageText',
                    'mappingRole',
                    'mappingMessageCreatedAt',
                    'mappingTimestamp',
                    'mappingMessageStatus',
                    'mappingMessageMetadata',
                    'mappingAttachments',
                ],
            },
            {
                label: 'Attachment mappings',
                isCollapsible: true,
                properties: [
                    'mappingAttachmentId',
                    'mappingAttachmentName',
                    'mappingAttachmentType',
                    'mappingAttachmentSize',
                    'mappingAttachmentUrl',
                    'mappingAttachmentUploadedUrl',
                    'mappingAttachmentStorageKey',
                    'mappingAttachmentStatus',
                    'mappingAttachmentError',
                ],
            },
        ],
        customStylePropertiesOrder: [
            {
                label: 'Layout',
                isCollapsible: true,
                properties: ['fontFamily', 'messagesAreaBgColor', 'messagesAreaPadding'],
            },
            {
                label: 'Assistant messages',
                isCollapsible: true,
                properties: [
                    'messageShowTimestamp',
                    'messageBgColor',
                    'messageTextColor',
                    'messageFontSize',
                    'messageFontWeight',
                    'messageFontFamily',
                    'messageBorder',
                    'messageRadius',
                ],
            },
            {
                label: 'User messages',
                isCollapsible: true,
                properties: [
                    'ownMessageShowTimestamp',
                    'ownMessageBgColor',
                    'ownMessageTextColor',
                    'ownMessageFontSize',
                    'ownMessageFontWeight',
                    'ownMessageFontFamily',
                    'ownMessageBorder',
                    'ownMessageRadius',
                ],
            },
            {
                label: 'Input',
                isCollapsible: true,
                properties: [
                    'inputBgColor',
                    'inputAreaBorder',
                    'textareaBorder',
                    'textareaBorderHover',
                    'textareaBorderFocus',
                    'inputTextColor',
                    'inputFontSize',
                    'inputFontWeight',
                    'inputFontFamily',
                    'inputPlaceholderColor',
                    'inputHeight',
                    'inputBorderRadius',
                ],
            },
            {
                label: 'Actions',
                isCollapsible: true,
                properties: [
                    'sendIcon',
                    'sendIconColor',
                    'sendIconSize',
                    'attachmentIcon',
                    'attachmentIconColor',
                    'attachmentIconSize',
                    'removeIcon',
                    'removeIconColor',
                    'removeIconSize',
                    'sendButtonBgColor',
                    'sendButtonHoverBgColor',
                    'sendButtonBorder',
                    'sendButtonBorderRadius',
                    'sendButtonSize',
                ],
            },
        ],
    },
    triggerEvents: [
        {
            name: 'messageSent',
            label: { en: 'On message sent' },
            event: {
                message: {
                    id: 'msg-1',
                    role: 'user',
                    content: 'Analyze this file',
                    status: 'completed',
                    createdAt: new Date().toISOString(),
                    attachments: [],
                },
                files: [],
            },
        },
        {
            name: 'filesSelected',
            label: { en: 'On files selected' },
            event: { files: [], attachments: [], rejected: [] },
        },
        {
            name: 'fileRemoved',
            label: { en: 'On file removed' },
            event: { attachment: {}, file: {}, index: 0 },
        },
        {
            name: 'uploadStarted',
            label: { en: 'On upload started' },
            event: { message: {}, files: [], attachments: [] },
        },
        {
            name: 'uploadCompleted',
            label: { en: 'On upload completed' },
            event: { message: {}, response: {} },
        },
        {
            name: 'uploadFailed',
            label: { en: 'On upload failed' },
            event: { message: {}, error: 'Upload failed' },
        },
        {
            name: 'assistantResponseStarted',
            label: { en: 'On assistant response started' },
            event: { message: {} },
        },
        {
            name: 'assistantResponseCompleted',
            label: { en: 'On assistant response completed' },
            event: { message: {}, response: {} },
        },
        {
            name: 'assistantResponseFailed',
            label: { en: 'On assistant response failed' },
            event: { message: {}, error: 'Assistant failed' },
        },
        {
            name: 'retryClicked',
            label: { en: 'On retry clicked' },
            event: { message: {}, retryMessage: {} },
        },
        {
            name: 'messageCopied',
            label: { en: 'On message copied' },
            event: { message: {}, content: 'Copied text', copied: true },
        },
        {
            name: 'conversationCleared',
            label: { en: 'On conversation cleared' },
            event: {},
        },
        {
            name: 'attachmentClick',
            label: { en: 'On attachment click' },
            event: { attachment: {} },
        },
        {
            name: 'pendingAttachmentClick',
            label: { en: 'On pending attachment click' },
            event: { attachment: {}, file: {}, index: 0 },
        },
        {
            name: 'messageRightClick',
            label: { en: 'On message right click' },
            event: {
                message: {},
                position: { elementX: 0, elementY: 0, viewportX: 0, viewportY: 0 },
            },
        },
    ],
    actions: [
        {
            action: 'scrollToBottom',
            label: { en: 'Scroll to bottom' },
        },
        {
            action: 'clearConversation',
            label: { en: 'Clear conversation' },
        },
        {
            action: 'addMessage',
            label: { en: 'Add message' },
            args: [{ name: 'message', type: 'object', label: { en: 'Message' } }],
        },
    ],
    properties: {
        messages: {
            label: { en: 'Messages' },
            type: 'Info',
            section: 'settings',
            bindable: true,
            bindingValidation: {
                type: 'array',
                tooltip: 'Array of message objects.',
            },
        },
        initialMessages: {
            label: { en: 'Initial Messages' },
            type: 'Info',
            section: 'settings',
            bindable: true,
            bindingValidation: {
                type: 'array',
                tooltip: 'Used only when Messages is not bound.',
            },
        },
        disabled: {
            label: { en: 'Disabled' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: false,
        },
        apiMode: {
            label: { en: 'API Mode' },
            type: 'TextSelect',
            section: 'settings',
            bindable: true,
            defaultValue: 'external',
            options: {
                options: [
                    { value: 'external', label: 'External backend' },
                    { value: 'proxy', label: 'Backend proxy' },
                    { value: 'direct', label: 'Direct endpoint' },
                ],
            },
        },
        apiEndpoint: {
            label: { en: 'API Endpoint' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        apiAuthToken: {
            label: { en: 'Auth Token' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        apiHeaders: {
            label: { en: 'Headers' },
            type: 'Textarea',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        modelName: {
            label: { en: 'Model Name' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        isLoading: {
            label: { en: 'Is Loading' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: false,
        },
        isStreaming: {
            label: { en: 'Is Streaming' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: false,
        },
        allowAttachments: {
            label: { en: 'Allow Attachments' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        acceptedFileTypes: {
            label: { en: 'Accepted File Types' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'image/*,.pdf,.txt,.md,.csv,.json,text/*',
        },
        maxFileSizeMb: {
            label: { en: 'Max File Size MB' },
            type: 'Number',
            section: 'settings',
            bindable: true,
            defaultValue: 10,
            options: { min: 1, max: 100, step: 1 },
        },
        maxFilesPerMessage: {
            label: { en: 'Max Files Per Message' },
            type: 'Number',
            section: 'settings',
            bindable: true,
            defaultValue: 5,
            options: { min: 1, max: 20, step: 1 },
        },
        allowMultipleFiles: {
            label: { en: 'Allow Multiple Files' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        showFilePreviews: {
            label: { en: 'Show File Previews' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        userLabel: {
            label: { en: 'User Label' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'You',
        },
        assistantLabel: {
            label: { en: 'Assistant Label' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'Assistant',
        },
        placeholder: {
            label: { en: 'Placeholder' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'Message...',
        },
        inputPlaceholder: {
            label: { en: 'Input Placeholder' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'Message...',
        },
        emptyMessageText: {
            label: { en: 'Empty Text' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'Ask anything to get started.',
        },
        loadingText: {
            label: { en: 'Loading Text' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: 'Thinking...',
        },
        errorText: {
            label: { en: 'Error Text' },
            type: 'Text',
            section: 'settings',
            bindable: true,
            defaultValue: '',
        },
        enableMarkdown: {
            label: { en: 'Enable Markdown' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        enableCopyButton: {
            label: { en: 'Enable Copy' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        enableRetryButton: {
            label: { en: 'Enable Retry' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },
        enableClearButton: {
            label: { en: 'Enable Clear' },
            type: 'OnOff',
            section: 'settings',
            bindable: true,
            defaultValue: true,
        },

        mappingMessageId: { label: { en: 'Message ID' }, type: 'Formula', section: 'settings' },
        mappingMessageText: { label: { en: 'Message Text' }, type: 'Formula', section: 'settings' },
        mappingRole: { label: { en: 'Role' }, type: 'Formula', section: 'settings' },
        mappingMessageCreatedAt: { label: { en: 'Created At' }, type: 'Formula', section: 'settings' },
        mappingTimestamp: { label: { en: 'Timestamp' }, type: 'Formula', section: 'settings' },
        mappingMessageStatus: { label: { en: 'Status' }, type: 'Formula', section: 'settings' },
        mappingMessageMetadata: { label: { en: 'Metadata' }, type: 'Formula', section: 'settings' },
        mappingAttachments: { label: { en: 'Attachments' }, type: 'Formula', section: 'settings' },
        mappingAttachmentId: { label: { en: 'Attachment ID' }, type: 'Formula', section: 'settings' },
        mappingAttachmentName: { label: { en: 'Attachment Name' }, type: 'Formula', section: 'settings' },
        mappingAttachmentType: { label: { en: 'Attachment Type' }, type: 'Formula', section: 'settings' },
        mappingAttachmentSize: { label: { en: 'Attachment Size' }, type: 'Formula', section: 'settings' },
        mappingAttachmentUrl: { label: { en: 'Attachment URL' }, type: 'Formula', section: 'settings' },
        mappingAttachmentUploadedUrl: { label: { en: 'Uploaded URL' }, type: 'Formula', section: 'settings' },
        mappingAttachmentStorageKey: { label: { en: 'Storage Key' }, type: 'Formula', section: 'settings' },
        mappingAttachmentStatus: { label: { en: 'Attachment Status' }, type: 'Formula', section: 'settings' },
        mappingAttachmentError: { label: { en: 'Attachment Error' }, type: 'Formula', section: 'settings' },

        fontFamily: { label: { en: 'Font Family' }, type: 'FontFamily', section: 'style', bindable: true, defaultValue: 'inherit' },
        messagesAreaBgColor: { label: { en: 'Messages Background' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#ffffff' },
        messagesAreaPadding: { label: { en: 'Messages Padding' }, type: 'Spacing', section: 'style', bindable: true, defaultValue: '18px' },
        messageShowTimestamp: { label: { en: 'Assistant Timestamp' }, type: 'OnOff', section: 'style', bindable: true, defaultValue: true },
        ownMessageShowTimestamp: { label: { en: 'User Timestamp' }, type: 'OnOff', section: 'style', bindable: true, defaultValue: true },
        messageBgColor: { label: { en: 'Assistant Background' }, type: 'Color', section: 'style', bindable: true, defaultValue: 'transparent' },
        messageTextColor: { label: { en: 'Assistant Text' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#1f2937' },
        messageFontSize: { label: { en: 'Assistant Font Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '0.9375rem' },
        messageFontWeight: { label: { en: 'Assistant Font Weight' }, type: 'Text', section: 'style', bindable: true, defaultValue: '400' },
        messageFontFamily: { label: { en: 'Assistant Font Family' }, type: 'FontFamily', section: 'style', bindable: true, defaultValue: 'inherit' },
        messageBorder: { label: { en: 'Assistant Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: 'none' },
        messageRadius: { label: { en: 'Assistant Radius' }, type: 'Length', section: 'style', bindable: true, defaultValue: '8px' },
        ownMessageBgColor: { label: { en: 'User Background' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#f3f4f6' },
        ownMessageTextColor: { label: { en: 'User Text' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#111827' },
        ownMessageFontSize: { label: { en: 'User Font Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '0.9375rem' },
        ownMessageFontWeight: { label: { en: 'User Font Weight' }, type: 'Text', section: 'style', bindable: true, defaultValue: '400' },
        ownMessageFontFamily: { label: { en: 'User Font Family' }, type: 'FontFamily', section: 'style', bindable: true, defaultValue: 'inherit' },
        ownMessageBorder: { label: { en: 'User Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: '1px solid #e5e7eb' },
        ownMessageRadius: { label: { en: 'User Radius' }, type: 'Length', section: 'style', bindable: true, defaultValue: '18px' },
        inputBgColor: { label: { en: 'Input Background' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#ffffff' },
        inputAreaBorder: { label: { en: 'Input Border Top' }, type: 'Border', section: 'style', bindable: true, defaultValue: '1px solid #e5e7eb' },
        textareaBorder: { label: { en: 'Textarea Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: '1px solid #d1d5db' },
        textareaBorderHover: { label: { en: 'Textarea Hover Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: '1px solid #9ca3af' },
        textareaBorderFocus: { label: { en: 'Textarea Focus Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: '1px solid #111827' },
        inputTextColor: { label: { en: 'Input Text' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#111827' },
        inputFontSize: { label: { en: 'Input Font Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '0.9375rem' },
        inputFontWeight: { label: { en: 'Input Font Weight' }, type: 'Text', section: 'style', bindable: true, defaultValue: '400' },
        inputFontFamily: { label: { en: 'Input Font Family' }, type: 'FontFamily', section: 'style', bindable: true, defaultValue: 'inherit' },
        inputPlaceholderColor: { label: { en: 'Placeholder Color' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#9ca3af' },
        inputHeight: { label: { en: 'Input Height' }, type: 'Length', section: 'style', bindable: true, defaultValue: '44px' },
        inputBorderRadius: { label: { en: 'Input Radius' }, type: 'Length', section: 'style', bindable: true, defaultValue: '12px' },
        sendIcon: { label: { en: 'Send Icon' }, type: 'SystemIcon', section: 'style', bindable: true, defaultValue: 'send' },
        sendIconColor: { label: { en: 'Send Icon Color' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#ffffff' },
        sendIconSize: { label: { en: 'Send Icon Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '18px' },
        attachmentIcon: { label: { en: 'Attachment Icon' }, type: 'SystemIcon', section: 'style', bindable: true, defaultValue: 'paperclip' },
        attachmentIconColor: { label: { en: 'Attachment Icon Color' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#374151' },
        attachmentIconSize: { label: { en: 'Attachment Icon Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '18px' },
        removeIcon: { label: { en: 'Remove Icon' }, type: 'SystemIcon', section: 'style', bindable: true, defaultValue: 'x' },
        removeIconColor: { label: { en: 'Remove Icon Color' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#374151' },
        removeIconSize: { label: { en: 'Remove Icon Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '14px' },
        sendButtonBgColor: { label: { en: 'Send Button Background' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#111827' },
        sendButtonHoverBgColor: { label: { en: 'Send Button Hover' }, type: 'Color', section: 'style', bindable: true, defaultValue: '#374151' },
        sendButtonBorder: { label: { en: 'Send Button Border' }, type: 'Border', section: 'style', bindable: true, defaultValue: 'none' },
        sendButtonBorderRadius: { label: { en: 'Send Button Radius' }, type: 'Length', section: 'style', bindable: true, defaultValue: '12px' },
        sendButtonSize: { label: { en: 'Send Button Size' }, type: 'Length', section: 'style', bindable: true, defaultValue: '42px' },
    },
};
